# Generated by Django 4.2.5 on 2023-10-02 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='изображение')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
